# Generated by Django 4.2.1 on 2023-06-16 14:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manufacture", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
    ]
