# Generated by Django 4.2.1 on 2023-06-16 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manufacture", "0002_delete_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="review",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manufacture.review",
            ),
        ),
    ]
